# スタック名：cmn-stack
# 説明：共通環境SGテンプレート 汎用Linuxサーバセキュリティグループ用テンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-linux-sg.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 汎用Linuxサーバセキュリティグループ作成テンプレート
Parameters:
  VPCId:
    Type: String
  VPCCidrBlock:
    Type: String
  TagCreatebyKey:
    Type: String
  TagCreatebyValue: 
    Type: String
Resources:
  CmnLinuxSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allow SSH access"
      GroupName: "cmn-linux-sg"
      SecurityGroupEgress: 
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCId
      Tags:
        - Key: !Ref TagCreatebyKey
          Value: !Ref TagCreatebyValue
Outputs:
  CmnLinuxSGId:
    Value: !Ref CmnLinuxSG
    Description: "CmnLinuxSG id"