# スタック名：cmn-stack
# 説明：共通環境 VPCテンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-vpc.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 共通VPC作成テンプレート
Parameters:
  VPCCidrBlock:
    Type: String
  TagCreatebyKey:
    Type: String
  TagCreatebyValue: 
    Type: String
Resources:
  CmnVPC: 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags: 
        - Key: "Name"
          Value: "cmn-vpc"
        - Key: !Ref TagCreatebyKey
          Value: !Ref TagCreatebyValue
  CmnInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: "Name"
          Value: "cmn-igw"
        - Key: !Ref TagCreatebyKey
          Value: !Ref TagCreatebyValue
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref CmnInternetGateway
      VpcId: !Ref CmnVPC
Outputs:
  CmnVPCId:
    Value: !Ref CmnVPC
    Description: "cmn-vpc VPC id"
  CmnVPCCidrBlock:
    Value: !GetAtt CmnVPC.CidrBlock
    Description: "cmn-vpc VPC cidr block"
  CmnIgwId:
    Value: !Ref CmnInternetGateway
    Description: "cmn-igw IGW id"