# スタック名：cmn-stack
# 説明：共通環境 mainテンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/main.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 共通環境Stack
Parameters:
  VPCCidrBlock:
    Type: String
    Default: "10.0.0.0/16"
    Description: "specify the IP address range of the VPC"
Mappings: 
  DefaultTag: 
    CreateBy: 
      key: "create-by"
      value: "CloudFormation"
  ChildStackVar:
    CmnVPCStack:  
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-vpc.yml"
    CmnLinuxSGStack: 
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-linux-sg.yml"
    BastionLinuxSGStack:  
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/bastion-linux-sg.yml"
Resources:
  CmnVPCStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, CmnVPCStack, TempleteUrl]
      Parameters:
        VPCCidrBlock: !Ref VPCCidrBlock
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]
  CmnLinuxSGStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, CmnLinuxSGStack, TempleteUrl]
      Parameters:
        VPCId: !GetAtt CmnVPCStack.Outputs.CmnVPCId
        VPCCidrBlock: !GetAtt CmnVPCStack.Outputs.CmnVPCCidrBlock
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]