# スタック名：cmn-stack
# 説明：共通環境 mainテンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/main.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 共通環境Stack
Mappings: 
  DefaultTag: 
    CreateBy: 
      key: "create-by"
      value: "CloudFormation"
  ChildStackVar:
    CmnVPCStack:  
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-vpc.yml"
      CidrBlock: "10.0.0.0/16"
    CmnPubSNStack: 
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-pub-sn.yml"
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: "ap-northeast-1a"
    CmnLinuxSGStack: 
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/cmn-linux-sg.yml"
    BastionLinuxSGStack:  
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn/bastion-linux-sg.yml"
Resources:
  CmnVPCStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, CmnVPCStack, TempleteUrl]
      Parameters:
        VPCCidrBlock: !FindInMap [ChildStackVar, CmnVPCStack, CidrBlock]
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]
  CmnPubSNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, CmnPubSNStack, TempleteUrl]
      Parameters: 
        VPCId: !GetAtt CmnVPCStack.Outputs.CmnVPCId
        IgwId: !GetAtt CmnVPCStack.Outputs.CmnIgwId
        SubnetCidrBlock: [ChildStackVar, CmnPubSNStack, CidrBlock]
        AvailabilityZone: [ChildStackVar, CmnPubSNStack, AvailabilityZone]
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]
  CmnLinuxSGStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, CmnLinuxSGStack, TempleteUrl]
      Parameters:
        VPCId: !GetAtt CmnVPCStack.Outputs.CmnVPCId
        VPCCidrBlock: !GetAtt CmnVPCStack.Outputs.CmnVPCCidrBlock
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]