# スタック名：cmn-ci-stack
# 説明：共通CI基盤 Terraformインスタンステンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn-ci/cmn-ci-terraform.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 共通CI基盤　Terraform Stack
Parameters:
  VPCId: 
    Type: String
  SubnetId: 
    Type: String
  SecurityGroupId: 
    Type: String
  InstanceName: 
    Type: String
  PrivateIpAddr: 
    Type: String
  TagCreatebyKey:
    Type: String
  TagCreatebyValue: 
    Type: String
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0f310fced6141e627" #Amazon Linux 2 AMI
      InstanceType: "t2.micro"
      KeyName: "default-key"
      SecurityGroupIds: 
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      PrivateIpAddress: !Ref PrivateIpAddr
      #UserData:
      #  Fn::Base64: |
      #    #!/bin/bash
      #    sudo curl -O https://releases.hashicorp.com/terraform/1.1.6/terraform_1.1.6_linux_amd64.zip
      #    sudo unzip terraform_1.1.6_linux_amd64.zip -d /usr/local/bin/
      #    sudo rm -f terraform_1.1.6_linux_amd64.zip
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
        - Key: !Ref TagCreatebyKey
          Value: !Ref TagCreatebyValue
  #EIP
  ElasticIp:
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      InstanceId: !Ref Instance
Outputs:
  PublicDnsName:
    Value: !GetAtt Instance.PublicDnsName