# スタック名：cmn-ci-stack
# 説明：共通CI基盤 mainテンプレート
# URL:https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn-ci/main.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: 共通CI基盤
Parameters:
  VPCId: 
    Type: String
  SubnetId: 
    Type: String
  SecurityGroupId: 
    Type: String
Mappings: 
  DefaultTag: 
    CreateBy: 
      key: "create-by"
      value: "CloudFormation"
  ChildStackVar:
    TerraformStack:  
      TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn-ci/cmn-ci-terraform.yml"
      InstanceName: "cmn-ci-terraform"
      PrivateIpAddr: "10.0.0.10"
    #AnsibleStack: 
    #  TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn-ci/cmn-ci-ansible.yml"
    #JenkinsStack: 
    #  TempleteUrl: "https://s3.ap-northeast-1.amazonaws.com/nanbara-cf-templete/cmn-ci/cmn-ci-jenkins.yml"
Resources:
  TerraformStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !FindInMap [ChildStackVar, TerraformStack, TempleteUrl]
      Parameters:
        VPCId: !Ref VPCId
        SubnetId: !Ref SubnetId
        SecurityGroupId: !Ref SecurityGroupId
        InstanceName: !FindInMap [ChildStackVar, TerraformStack, InstanceName]
        PrivateIpAddr: !FindInMap  [ChildStackVar, TerraformStack, PrivateIpAddr]
        TagCreatebyKey: !FindInMap [DefaultTag, CreateBy, key]
        TagCreatebyValue: !FindInMap [DefaultTag, CreateBy, value]
Outputs:
  TerraformPublicDnsName:
    Value: !GetAtt TerraformStack.Outputs.PublicDnsName
    Description: "public dns name of cmn-ci-terraform"